baseURL = "/"
languageCode = "en-us"
title = "Martín Rodriguez"
theme = "hello-friend-ng"

[author]
  name = "Martín Rodriguez"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Signal Processing and Machine Learning"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Martín Rodriguez's homepage"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts/"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#181a1b"


  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = true  # Set "text-align: justify" to .post-content.

  statisticsEnabled = false

  # Custom footer
  # If you want, you can easily override the default footer with your own content.
  #
  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/mtrpdx"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/mtrpdx"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/martintrodriguez"

  [[params.social]]
    name = "email"
    url  = "mailto:mtrpdx@gmail.com"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
    category = "blog"
    tag      = "tags"

[languages]
  [languages.en.params]
    title = "Martín Rodriguez"
    subtitle = "Electrical and Computer Engineering"
    keywords = ""
    readOtherPosts = "Read other posts"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
      logoText = "mtrpdx/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
  [[menu.main]]
    identifier = "reading"
    name       = "Reading List"
    url        = "/reading"
